development:
  secret_key_base: development_secret_key_base_1234567890123456789012345678901234567890123456789012345678901234567890

test:
  secret_key_base: test_secret_key_base

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

